### ISSUE TITLE
Temporal control

### ISSUE THREAD

**Issue by Dionysus7777777** [m-abr/FCPCodebase#11]
Could you please explain how the underlying execution logic works here? Does it execute all the code every 0.02 seconds?
If I want to achieve a scenario where, at a specific time point, for example, 3 seconds after the kickoff, all members stand still, where should I make modifications?
I tried modifying it in "think and send," but it didn't work.

**Comment by m-abr** [comment]
Yes, `think_and_send` is executed every 0.02 seconds. To stop all robots after 3 seconds (game time), change this:
```
        #--------------------------------------- 2. Decide action



        if PM == w.M_GAME_OVER:
            pass
        elif PM_GROUP == w.MG_ACTIVE_BEAM:
        (...)
```
Into this:
```
        #--------------------------------------- 2. Decide action


        if w.time_game > 3:
            pass
        elif PM == w.M_GAME_OVER:
            pass
        elif PM_GROUP == w.MG_ACTIVE_BEAM:
        (...)
```
Please let me know if this explanation is clear enough.

**Comment by Dionysus7777777** [comment]
Yes, very clear. I want to know if all the code is executed every 0.02 seconds, or is it just the Agent code?

**Comment by Dionysus7777777** [comment]
Yes, very clear. But I want to know if all the code is executed every 0.02 seconds, or is it just the Agent code?

**Comment by m-abr** [comment]
When you run the agent either directly via `/Run_Player.py `or indirectly through `/start.sh`, the following code snippet from 
`/Run_Player.py` is executed repeatedly every 0.02 seconds:

```
while True:
    player.think_and_send()
    player.scom.receive()
```

Here's what each method does:

1.    player.think_and_send(): This method determines the next action to take and sends this information to the server.
2.    player.scom.receive(): This method waits for and receives the server's response, updating internal state variables accordingly. These variables are instance variables of `self.world` and `self.world.robot`, which belong to classes defined in 
`/world/World.py` and `/world/Robot.py` respectively.

It's important to note that certain updates occur at different intervals:

-  Some variables, including internal robot state information like joint positions, internal sensors, and game statistics, are updated every 0.02 seconds.
-   However, certain data, such as self-localization and ball position, relies on visual information, which is sent by the server at a slower rate (every 0.04 seconds).

I think this already answers your question, but to summarize, besides `think_and_send`, there is a lot of code running every 0.02 s to update all the internal variables that store the environment state (with some updates occurring at a slower pace of 0.04 seconds due to their dependency on visual input from the server).
