### ISSUE TITLE
How to stop referee from beaming player

### ISSUE THREAD

**Issue by AllenChienXXX** [m-abr/FCPCodebase#12]
I tried the methods in the **Referee Intervention**, but it's still not working and I also try different mode. when I'm training, the robot always get stuck in the middle of the court. Is there a solution to this issue?
![Screenshot from 2024-03-31 16-17-26](https://github.com/m-abr/FCPCodebase/assets/87592678/f100d504-fd5c-4ab5-9658-b59f897e2198)

**Comment by m-abr** [comment]
I'm not entirely sure about the specific issue you're facing. Are you experiencing a situation where the robot and simulation are completely frozen? Or is it that the simulation is running, but the robot isn't being positioned where you expect it to be?

### If the robot and simulation are frozen:

This could be due to various factors depending on how your code is implemented. One thing to check is whether the code gets stuck at the `reset` or `step` functions. Additionally, ensure that `self.sync()` is being called at least once within both functions.

### If the simulation is running but the robot isn't being placed correctly:

I think in the latest server versions, it's preferable to keep the Referee on, otherwise the server might crash.

Before the game starts (while in `BeforeKickOff` mode), the referee will continuously beam the robot out of the opponent's field half. It seems like you're currently beaming the robot to the opponent's field using positive X coordinates. To troubleshoot, try using negative X coordinates to ensure the robot is being correctly placed.

If you **need** to beam the robot to the opponent's field half, I'd suggest setting the game mode to `GameOver` **before** beaming the robot, using `self.player.scom.unofficial_set_play_mode("GameOver")` at the end of the gym’s __init__ method, as suggested in the documentation.
