### ISSUE TITLE
start_penalty.sh

### ISSUE THREAD

**Issue by Dionysus7777777** [m-abr/FCPCodebase#19]
I followed the instruction manual to initiate the penalty kick mode.
When I initiate the penalty kick mode, I found that after our side activated the penalty kick mode, a forward and a goalkeeper from our team came onto the field, but the opposing penalty taker was unable to enter the field.

**Comment by m-abr** [comment]
What specific steps have you taken exactly? Here's how I would approach it:

### Change the server configuration to penalty shootout mode

```
python Run_Utils.py
# input '0' to select 'Server'
# make sure 'Penalty Shootout' is 'On'
```

|        Setting        |  Value  |                            Description                             |
|-----------------------|---------|--------------------------------------------------------------------|
|   0-Official Config   |  Off    |  Configuration used in official matches                            |
|   1-Penalty Shootout  |  **On**     |  Server's Penalty Shootout mode                                   |
| ... | ... | ... |

### Start or restart the server

`rcssserver3d`
(note that the server must be restarted every time its configuration variables are changed)

### Launch 1st team

`./start_penalty.sh `

### Launch 2nd team

`./start_penalty_debug.sh`
(note that this step only works because the team name used in `start_penalty.sh` is different from the team name used in `start_penalty_debug.sh`, otherwise the team will be unable to enter the field).

**Comment by Dionysus7777777** [comment]
thanks
