### ISSUE TITLE
Run_Utils.py error

### ISSUE THREAD

**Issue by AllenChienXXX** [m-abr/FCPCodebase#2]
Hi, 

I'm running this repo on macOS M2 chip. I have installed roboviz but not simspark since I want to try if I can run some based agent first. When I'm running `python3 Run_Utils.py` , I got the following error:

C++ modules: ['a_star', 'ball_predictor', 'localization']
Using Pybind11 includes: '-I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -I/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pybind11/include'
Building: a_star...                     Aborting! Building errors:
g++ -O3 -shared -std=c++11 -fPIC -Wall -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -I/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pybind11/include -o a_star.so a_star.cpp lib_main.cpp
 a_star.cpp:521:16: error: variable-sized object may not be initialized
    float obst[given_obst_size*4/5+16] = {
               ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [all] Error 1

**Comment by m-abr** [comment]
Hi Allen,

Thank you for reporting this issue. Although that module's code was written primarily in C++, it was often optimized with C-style structures.
Variable length arrays are a C-style structure that is not legal in C++, although some compilers allow it.

Fixing the issue is relatively simple but to understand the extent of the problem I would ask you to please change the array length initializer to a large constant, say 5000, and then run ```python3 Run_Utils.py``` again:

In  **FCPCodebase/cpp/a_star/a_star.cpp**:

Change line 521:
`float obst[given_obst_size*4/5+16] = {`

To this:
`float obst[5000] = {`

Thank you!
