### ISSUE TITLE
packaging the binary code

### ISSUE THREAD

**Issue by Dionysus7777777** [m-abr/FCPCodebase#20]
Sorry to bother you again. After packaging the binary code, I successfully generated the 'dist' file. However, there seems to be a slight issue with this file. It works fine on my computer, but on others', there are some errors. Could you please help me understand why this is happening?

![微信图片_20240429200941](https://github.com/m-abr/FCPCodebase/assets/144111054/6790bb7f-6a85-4f00-bc36-7797d9ffcb77)

**Comment by m-abr** [comment]
It seems that you might have inadvertently set parameter **-P** to **False**. 
Parameter **-P** accepts only _int_ values (**0** or **1**).
The parameter data types are specified in `/scripts/commons/Script.py`.

In the same folder as the binary you should have the start script you are using to invoke the team (e.g. `start.sh`) and the configuration file `config.json`, which is automatically created on the first run.

The problem could lie in either the start script or the configuration file. 
Please check if your start script contains something like this:
```
for i in {1..11}; do
  ./fcp -i $host -p $port -u $i -t FCPortugal -P False &         # '-P False' isn't valid, use '-P 0'
done
```

Or if your `config.json` file has something like this:
```
"P": [
        "Penalty Shootout",
        "False"                  # not a valid value, use "0" instead
    ],
```

Note: the configuration provided by the start script overrides the default values in `config.json`.

**Comment by Dionysus7777777** [comment]
I encountered a rather strange issue. My earlier version could be packaged normally. However, my newer version cannot be packaged. I have checked, and I haven't added any new files, so this shouldn't be a potential issue. Specifically, when I execute the bundle.sh file, it can package properly and generate the dist files. But when I run ./start.sh in the dist file, I encounter this problem.
<img width="458" alt="image" src="https://github.com/m-abr/FCPCodebase/assets/144111054/6a770fc3-6db4-4166-aecd-94f3302b42e8">

**Comment by m-abr** [comment]
Please follow these steps to resolve the issue:

1. Delete the following folders:
   - `/bundle/dist/`
   - `/bundle/build/`

2. Next, remove the compiled C++ modules:
   - `/cpp/a_star/a_star.so`
   - `/cpp/ball_predictor/ball_predictor.so`
   - `/cpp/localization/localization.so`

3. Now, execute the following command to recompile the C++ modules:
```
python Run_Utils.py
```

4. Finally, rerun bundle.sh and check if the problem is resolved.

---

If the problem persists, there might be a conflict with multiple Python versions installed on your computer. Please verify the Python version used to compile the C++ modules by inspecting these files:
   - `/cpp/a_star/a_star.c_info`
   - `/cpp/ball_predictor/ball_predictor.c_info`
   - `/cpp/localization/localization.c_info`

**Comment by Dionysus7777777** [comment]
Thank you for your help. We had already resolved the issue earlier, but I forgot to reply and close the case. My apologies for that.
