### ISSUE TITLE
About Basic_Run usage

### ISSUE THREAD

**Issue by Dm15056376549** [m-abr/FCPCodebase#22]
Now I get my model result from gym, what should i do to add the Run motion into my agent`s action?

**Comment by m-abr** [comment]
Please refer to [Section 10](https://docs.google.com/document/d/1aJhwK2iJtU-ri_2JOB8iYvxzbPskJ8kbk_4rb3IK3yc/edit#heading=h.psp5s0oytqe3) of the documentation (and more specifically Section 10.3 for information on how to integrate trained models).

**Comment by Dm15056376549** [comment]
thanks,you r great.Could i ask if i can accelerate the gym training processes by gpu with cuda?

**Comment by m-abr** [comment]
The GPU can only be used during policy updates, not during episode rollouts, which is the most time-consuming task. This limitation exists because the server (rcssserver3d/SimSpark) relies solely on the CPU. Therefore, using the GPU offers no practical advantage in this context.

However, you can enable it by changing every instance of `device="cpu"` to `device="auto"` or `device="cuda"` in the gym you are using. This change will instruct PyTorch to use the GPU for policy updates.
