### ISSUE TITLE
Basic_Run Crashes

### ISSUE THREAD

**Issue by doctochen** [m-abr/FCPCodebase#25]
I encountered an error while testing the Basic_Run from the codebase, as shown in the attached image ![image](https://github.com/user-attachments/assets/0fffbb67-8630-4e6e-9a84-ec2beb614b42) I have tried running it three times, and each time after about one to two hours (I didn't measure the exact duration), the same error occurred. After the error, the script immediately stopped, but the rcssserver3d process was still alive. Prior to the error, it seemed to be running normally?

I suspect that this issue might be due to one of the following reasons:

- The rcssserver3d configuration may have been inadvertently modified by me.
- There could be a misuse.
- The environment setup might have some problems.

If you could provide any assistance, it would be greatly appreciated.

**Comment by m-abr** [comment]
I've run the `Basic_Run` for 8 hours (~16M time steps) on a clean installation of Ubuntu 22.04, using the latest version of rcssserver3d (v0.7.7).
![Screenshot from 2024-10-16 02-09-32](https://github.com/user-attachments/assets/66e88cc8-262c-4b9a-8a37-89e5af1193df)
After this period, I opened RoboViz on port 4200 to check the learning progression, and everything seems to be working as expected. The robot is running smoothly. (Note: I don't recommend doing this while training, as it may affect performance.)

The server configuration I used can be seen below:
![Screenshot from 2024-10-16 02-24-02](https://github.com/user-attachments/assets/23320512-67f2-4726-9c93-0c9c42dfb725)
If you still encounter the issue after applying this configuration, please let me know.

**Comment by doctochen** [comment]
@m-abr Thank you very much for the help provided! We have modified the server's configuration, and the Basic_Run training can now be used normally. We have successfully obtained the best_model.zip.pkl, and we've also achieved normal results in the Test. However, we still have some other questions. We are not clear on how to use the best_model.zip.pkl. I read through the implementation example in the codebase, specifically behaviors/custom/Fall/Fall.py, and found that its observer and execute methods are quite similar to the observer and step functions in scripts/gyms/Fall.py. Can I basically refer to these methods in scripts/gyms/Basic_Run.py to utilize the best_model.zip.pkl for adding new skills? Are there any precautions or considerations we should be aware of?

In addition, our team lacks experience in using reinforcement learning and other techniques to train actions, and we are eager to learn more about the technical details. Are there any open-source papers or resources that we could reference? We really appreciate your help and sharing.

**Comment by m-abr** [comment]
Yes, you can use those methods to access **best_model.zip.pkl** from within a gym and build new behaviors on top of it. This aligns with hierarchical learning and fits the layered learning paradigm proposed by Peter Stone [1], though there are variations [2]. Once you create a behavior (e.g., _behaviors/custom/Fall/Fall.py_), you can execute it by calling `self.player.behavior.execute("Fall")`, similar to how **Basic_Run.py** calls the `Step` behavior with `self.player.behavior.execute("Step", ...)`. This allows you to reuse previously learned behaviors in new scenarios.

Under the hood, calling `self.player.behavior.execute("Step", ...)` triggers the `execute` method in _behaviors/custom/Step/Step.py_, generating joint target positions that are stored in `self.values_l` and `self.values_r`. These are converted into joint angular velocities via `self.world.robot.set_joints_target_position_direct()`, and the values are stored in this array: `self.world.robot.joints_target_speed`. When you call `self.sync()`, these values are sent to the _rcssserver3d_, so you can override them before synchronizing.

So, one way of learning something on top of the `Step` behavior would be to call `self.player.behavior.execute("Step", ...)` from a gym and then adding the output of the neural network to the values in `self.world.robot.joints_target_speed` before synchronizing. However, directly manipulating joint positions tends to yield better results than adjusting angular velocities [3], due to numerical stability but also information loss from saturation clipping. 

Therefore, in **Basic_Run.py**, after executing the `Step` behavior, the joint target positions are accessed via `self.step_obj.values_l` and `self.step_obj.values_r`. The values are then modified by the policy and sent to `r.set_joints_target_position_direct()` which overrides `self.world.robot.joints_target_speed` before synchronizing with the server.

Caveats
--

When learning a new behavior on top of an existing one, a key issue is that the first behavior may not generalize well to new states introduced by the second task. For instance, if the first behavior was trained for a specific gait, it might produce unstable outputs when forced to deviate. This is because the first network hasn’t encountered these states before, limiting its adaptability. One way to address this is to avoid freezing the first network entirely or to design tasks that minimize such hierarchical incompatibilities. It's worth mentioning that the `Step` behavior used in **Basic_Run.py** follows an open-loop control approach and isn't driven by a neural network policy.


More References
--

In addition to the references above, I recommend this paper [4], which offers valuable insights into key aspects I found important when training a running behavior from scratch, without relying on predefined models like the Step behavior. For foundational concepts, I highly recommend Sutton and Barto's book [5].

---

[1] Peter Stone. Layered Learning in Multiagent Systems: A Winning Approach to Robotic Soccer. The MIT Press, 03 2000. ISBN 9780262284448.

[2] Patrick MacAlpine and Peter Stone. Overlapping layered learning. Artificial Intelligence, 254:21–43, 2018.

[3] Miguel Abreu, Nuno Lau, Armando Sousa, and Luís Paulo Reis. Learning low level skills from scratch for humanoid robot soccer using deep reinforcement learning. In 2019 IEEE International Conference on Autonomous Robot Systems and Competitions (ICARSC), pages 256–263, Porto, Portugal, 2019. IEEE.

[4] Miguel Abreu, Luís Paulo Reis, and Nuno Lau. Learning to run faster in a humanoid robot soccer environment through reinforcement learning. In
RoboCup 2019: Robot World Cup XXIII, pages 3–15, Sydney, Australia, 2019. Springer.

[5] Richard S. Sutton and Andrew G. Barto. Reinforcement learning: An introduction. MIT press, Cambridge, Massachusetts, USA, 2nd edition, 2018.
